### ISSUE TITLE
add-on workspace will not launch on mac

### ISSUE THREAD

**Issue by holdupitsAyyM80** [HyperiumClient/Addon-Workspace#2]
will either have one of these two:
(If run like in the video)
[10:50:16] [main/INFO]: Extra: [--tweakclass, cc.hyperium.launch.HyperiumTweaker]
[10:50:16] [main/INFO]: Running with arguments: [--userProperties, {}, --assetsDir, /Users/brownie/.gradle/caches/minecraft/assets, --assetIndex, 1.8, --accessToken{REDACTED}, --version, 1.8.9, --tweakclass, cc.hyperium.launch.HyperiumTweaker]
[10:50:16] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[10:50:16] [main/INFO]: Using primary tweak class name net.minecraft.launchwrapper.VanillaTweaker
[10:50:16] [main/INFO]: Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
[10:50:16] [main/ERROR]: Unable to launch
java.lang.NoSuchMethodException: net.minecraft.client.Minecraft.main([Ljava.lang.String;)
    at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_40]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:132) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:26) [start/:?]

Process finished with exit code 0

------

If using runClient:

Description: Initializing game

java.lang.UnsatisfiedLinkError: org.bridj.cpp.com.COMRuntime.CoInitializeEx(JI)I
    at org.bridj.cpp.com.COMRuntime.CoInitializeEx(Native Method)
    at org.bridj.cpp.com.COMRuntime$1.initialValue(COMRuntime.java:231)
    at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
    at java.lang.ThreadLocal.get(ThreadLocal.java:170)
    at org.bridj.cpp.com.COMRuntime.initialize(COMRuntime.java:254)
    at org.bridj.cpp.com.COMRuntime.newInstance(COMRuntime.java:262)
    at org.bridj.cpp.com.COMRuntime.newInstance(COMRuntime.java:258)
    at cc.hyperium.SplashProgress.drawSplash(SplashProgress.java:111)
    at net.minecraft.client.Minecraft.drawSplashScreen(Minecraft.java:3818)
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:452)
    at net.minecraft.client.Minecraft.run(Minecraft.java:358)
    at net.minecraft.client.main.Main.main(Main.java:113)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
    at GradleStart.main(GradleStart.java:26)
-- Head --
Stacktrace:
    at org.bridj.cpp.com.COMRuntime.CoInitializeEx(Native Method)
    at org.bridj.cpp.com.COMRuntime$1.initialValue(COMRuntime.java:231)
    at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
    at java.lang.ThreadLocal.get(ThreadLocal.java:170)
    at org.bridj.cpp.com.COMRuntime.initialize(COMRuntime.java:254)
    at org.bridj.cpp.com.COMRuntime.newInstance(COMRuntime.java:262)
    at org.bridj.cpp.com.COMRuntime.newInstance(COMRuntime.java:258)
    at cc.hyperium.SplashProgress.drawSplash(SplashProgress.java:111)
    at net.minecraft.client.Minecraft.drawSplashScreen(Minecraft.java:3818)
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:452)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.run(Minecraft.java:358)
    at net.minecraft.client.main.Main.main(Main.java:113)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
    at GradleStart.main(GradleStart.java:26)

i think someone might have already had a ticket on the discord for this, idk

**Comment by liach** [comment]
Redownload all the libraries for hyperium. Looks like a broken library.
